notifications: # set notification options
  slack:
    rooms:
      - ucsc-cgl:Edwfgt7MJEVZV9Lib3igueTF
    on_success: change
    on_failure: always
  email: false

language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py35,codecov
      python: '3.5'
    - env:
        - TOXENV=py36,codecov
      python: '3.6'
    - os: osx
      language: generic
      env:
        - TOXENV=py37
    - env:
        - TOXENV=py37,codecov
      python: '3.7'
    - env:
        - TOXENV=py38,codecov
      python: '3.8'
    - env:
        - TOXENV=pypy3,codecov
        - TOXPYTHON=pypy3
      python: 'pypy3'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      [[ $TOXENV =~ py3 ]] && brew upgrade python
      [[ $TOXENV =~ py2 ]] && brew install python@2
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
